- repos:
  - repo: local
    hooks:

      - id: check-readme-exists
        name: Check README.md Exists
        entry: bash -c 'if [ ! -f README.md ]; then echo "README.md file is missing!" >&2; exit 1; fi'

      - id: black
        name: Black Code Formatter
        entry: poetry run black
        language: system
        types: [python]
      
      - id: isort
        name: isort Import Sorter
        entry: poetry run isort
        language: system
        types: [python]

      - id: flake8
        name: Flake8 Linter
        entry: poetry run flake8
        language: system
        types: [python]

      - id: nbstripout
        name: Strip Output from Notebooks
        entry: poetry run nbstripout
        language: system
        types: [jupyter]